### ISSUE TITLE
[Blazor] Layout Breaking

### ISSUE THREAD

**Issue by douglassimaodev** [dotnet/Scaffolding#1321] opened 2020-04-16 19:54 UTC
blazor webassembly with asp.net core hosted

after scaffolding Identity, layout breaks, as it is adding wwwroot folder

**Comment by deepchoudhery** [comment] 2020-04-27 17:58
Hey @douglassimaodev are you using VS or the cli tool? Would like to know the version of the package, target framework of the blazor server.

**Comment by douglassimaodev** [comment] 2020-04-27 20:56
Hi @deepchoudhery I am using VS 2019 but now Updating for the latest version 
dotnet new -i Microsoft.AspNetCore.Components.WebAssembly.Templates::3.2.0-preview5.20216.8

this is not happening anymore, however now after the scaffolding, Server/Pages/_Layout.cshtml

does not have @RenderSection("Scripts", required: false)  so it gives me an error: '/Pages/Shared/_Layout.cshtml': 'Scripts'. To ignore an unrendered section call IgnoreSection("sectionName").


once I manually add this: "@RenderSection("Scripts", required: false)" in _Layout.cshtml it works

however, as it is adding 

<script src="/Identity/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="/Identity/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

coming from Areas/Identity/Pages/Account/Login.cshtml  = @section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

it is saying: jquery.validate.js:15 Uncaught ReferenceError: jQuery is not defined

as there is no jquery file in the project

somehow from default project after scaffolding it loses the files references:

<script src="/Identity/lib/jquery/dist/jquery.js"></script>
<script src="/Identity/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
<script src="/Identity/js/site.js?v=4q1jwFhaPaZgr8WAUSrux6hAuh0XDg9kPS3xIVq36I0"></script>

That gets added before the scaffolding

**Comment by deepchoudhery** [comment] 2020-04-28 23:21
This seems like a content issue. @danroth27 @HaoK any ideas?

**Comment by danroth27** [comment] 2020-06-13 01:32
Duplicate of #1325

**Closed by danroth27** 2020-06-13 01:32 UTC
