### ISSUE TITLE
Scaffolding is Downgrading Core.SqlServer and Core.Tools packages then failing 

### ISSUE THREAD

**Issue by danjhetherington** [dotnet/Scaffolding#1649] opened 2021-09-23 09:29 UTC
Scaffolding a MVC Controller using 5.0.10 packages of 

`Microsoft.EntityFrameworkCore.Tools` & `MicrosoftEntityFrameworkCore.SqlServer`
![err1](https://user-images.githubusercontent.com/37192365/134483985-56331191-d0be-4fc0-95ab-40fd500380df.PNG)

Every time I try to add the scaffold these Packages get downgraded to version 5.0.9 and then the scaffolding fails.
![err2](https://user-images.githubusercontent.com/37192365/134484335-bd3c02c2-b0a7-41e9-8c6b-7b9963279311.PNG)

**Comment by Ogglas** [comment] 2021-09-24 16:31
Adding to the description of @danjhetherington 

In a ASP.NET Core project I run `Add Controller` - `API Controller with actions, using Entity Framework` from Visual Studio 2019. 

[![enter image description here][1]][1]

I then get the following error:

> Error
> 
> There was an error running the selected code generator: 'Could not
> load file or assembly 'Microsoft.EntityFrameworkCore.SqlServer,
> Version=5.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
> The system cannot find the file specified.'

[![enter image description here][2]][2]

If I take a look at Git I can see that Visual Studio has automatically downgraded `Microsoft.EntityFrameworkCore.SqlServer` and `Microsoft.EntityFrameworkCore.Tools` to `5.0.9`.

[![enter image description here][3]][3]

If I run the exact same code again it will work. 

I'm running the latest `Microsoft Visual Studio Community 2019 Version 16.11.3` and all the latest NuGet packages. I can only update `Microsoft.EntityFrameworkCore.SqlServer` and `Microsoft.EntityFrameworkCore.Tools` that Visual Studio automatically downgraded.

[![enter image description here][4]][4]

Original SO Post:
https://stackoverflow.com/q/69316810/3850405

  [1]: https://i.stack.imgur.com/5CbQp.png
  [2]: https://i.stack.imgur.com/ZyLBT.png
  [3]: https://i.stack.imgur.com/EMHHi.png
  [4]: https://i.stack.imgur.com/9BMqi.png

**Comment by vijayrkn** [comment] 2021-11-04 16:02
This is the same issue as https://github.com/dotnet/Scaffolding/issues/1540. 

And the work-around is also the same i.e Running the scaffolder again fixes the issue. 

Closing this as a dupe of https://github.com/dotnet/Scaffolding/issues/1540 and bumping up the priority of this item.

**Closed by vijayrkn** 2021-11-04 16:02 UTC
Labels: PRI: 1 - Required
