### ISSUE TITLE
Identity Scaffolding to existing project is broken

### ISSUE THREAD

**Issue by RichardD2** [dotnet/Scaffolding#1555] opened 2021-04-15 13:47 UTC
### Describe the bug
Attempting to scaffold the Identity views into an existing .NET 5 project which references v5.0.5 of the Identity libraries does not work. The tool down-grades the NuGet package references, then complains that there are build errors because the site references a lower version of the packages than a referenced class library.

### To Reproduce
Using Visual Studio 2019 v16.9.4, create a new solution with two projects:

* A .NET 5.0 class library;
* An ASP.NET 5.0 site;

In the class library, reference `Microsoft.AspNetCore.Identity.EntityFrameworkCore` version `5.0.5`, and `Microsoft.EntityFrameworkCore` version `5.0.5`. Create a class derived from `IdentityContext`.

In the site, reference the class library, and reference `Microsoft.AspNetCore.Identity.UI` version `5.0.5`. Configure identity to use the context from the class library.

Verify that the solution builds without errors.

Right-click on the site and select "Add -> New Scaffolded Item". Walk through the steps to scaffold the Identity views, as described in [the documentation](https://docs.microsoft.com/en-gb/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio), selecting the correct context from the drop-down list.

After a while, the operation fails with an error:

![image](https://user-images.githubusercontent.com/2158265/114878965-ad4eb980-9df8-11eb-98e7-4b04ea32b13a.png)

The Identity and EF Core references in the site have been down-graded to version `5.0.4`, and the site now fails to build because the class library references a higher version!

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.202\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

Microsoft Visual Studio Professional 2019
Version 16.9.4
VisualStudio.16.Release/16.9.4+31205.134
Microsoft .NET Framework
Version 4.8.04084
Installed Version: Professional

**Comment by joseDelgado393** [comment] 2021-04-21 09:02
any solution? I have the same problem

**Comment by ashimaz** [comment] 2021-04-22 04:20
I'm my blazor client project entity framework api scaffolding does not work when I upgrade nuget to Microsoft.EntityFrameworkCore.SqlServer 5.0.5, to fix this issue had to downgrade to Microsoft.EntityFrameworkCore.SqlServer 5.0.4

**Comment by rr222cy** [comment] 2021-04-23 12:35
I can confirm this, and also that @ashimaz comment works as a temporary solution, it does however impact more packages. For example if using EF this also needs to be downgraded to 5.0.4 for the scaffolding to work as expected.

**Comment by deepchoudhery** [comment] 2021-06-07 20:09
Hey,
Packages have been updated for EF, and Identity. 
If possible, please retry the scenario and get back to me. There should be no downgrades and should work.

Let me know,
Deep

**Comment by michelmoorlag** [comment] 2021-07-01 06:25
I tried with 5.0.7 and it is still broken. The only way to scaffold an ef/identity item is to downgrade everything to 5.0.4.

**Comment by rr222cy** [comment] 2021-07-09 13:17
> Hey,
> Packages have been updated for EF, and Identity.
> If possible, please retry the scenario and get back to me. There should be no downgrades and should work.
> 
> Let me know,
> Deep

Hi!
I've just tested this with 5.0.7 on a new project and just as @michelmoorlag says it's still broken unfortunatley.

**Comment by deepchoudhery** [comment] 2021-07-09 16:29
@michelmoorlag  @rr222cy Hmm I think there is a version mismatch on my end. I will take a look very soon and reach back to y'all.

**Comment by flicwin** [comment] 2021-08-21 11:31
Created a new Blazor Net Core Hosted application with default IdentityServer & EntityFramework packages Version="5.0.9" and received the same critical error during a scaffolding attempt overriding all. I changed the packages down to 5.0.8 and ran the scaffold again which this time completed **successfully**.
Microsoft Visual Studio Community 2019 Preview
Version 16.11.0 Preview 2.0

**Comment by dekoeky** [comment] 2021-08-28 13:48
I'm having the same issue as @flicwin. Changing 5.0.9 package to 5.0.8 also solved the issue.

Microsoft Visual Studio Community 2019
Version 16.11.2


> Created a new Blazor Net Core Hosted application with default IdentityServer & EntityFramework packages Version="5.0.9" and received the same critical error during a scaffolding attempt overriding all. I changed the packages down to 5.0.8 and ran the scaffold again which this time completed **successfully**.
> Microsoft Visual Studio Community 2019 Preview
> Version 16.11.0 Preview 2.0

**Comment by flicwin** [comment] 2021-09-21 04:04
Since 5.0.10 I'm unable to roll anything back because the first order of business when scaffolding Identity is to bring the corresponding packages up to date - which means every attempt to scaffold returns a rollback error.
I have found an interim fix [here](https://clintmcmahon.com/there-was-an-error-running-the-selected-code-generator-in-net-core-5/) which solved my issue. This article was written in February and people have been thanking the author all year. I hope it helps you too.

**Comment by deepchoudhery** [comment] 2021-09-21 18:22
Hi,
A lot of these issues are primarily due to the packages that scaffolding enforces and the packages that the project templates/a project's csproj already consist of. I'm trying to come up with a more error free system. Unfortunately, it'll likely be for net6.0 starting out until I get to servicing updates for the net5.0, netcoreapp3.1.

**Comment by SoftCircuits** [comment] 2021-09-22 20:16
I've been having the same issue in multiple projects. If Microsoft won't fix this, can't they at least give me an error message that means something?

**Comment by izzyjere** [comment] 2021-10-11 14:31
With me I solved the issue by first moving all code in Page.razor.cs to Page.razor and temporatily commented out any references to Grpc Services and scaffolding worked. By the way all my packages were upto date.

**Comment by vijayrkn** [comment] 2021-11-08 18:23
This issue is fixed in the latest 6.0 version of the package.

**Closed by vijayrkn** 2021-11-08 18:23 UTC
Labels: PRI: 1 - Required

**Comment by urbanknight** [comment] 2022-08-09 19:05
I still get this issue in the latest version (6.0)

**Comment by izzyjere** [comment] 2022-08-10 05:53
I discovered that sometimes Visual Studio fails to download the packages due to network issues(slow) . Hence, you have to manually install Microsoft.VisualStudio.CodeGeneration.Design using the package manager and then try scaffolding.
