### ISSUE TITLE
 Problem with scaffolding with Db Context inheriting ApiAuthorizationDbContext

### ISSUE THREAD

**Issue by Oredna** [dotnet/Scaffolding#1352] opened 2020-06-11 19:42 UTC
When scaffolding a API Controller with actions, usung Entity Framework, I cant fint the Data context class. It empty in the form.

### Steps to reproduce

I create Blazor app, with .Net Core Server. If i chose to have authentication, the scaffolded AplicationDbContext is inheriting from ApiAuthorizationDbContext. If i try to scaffold Api Controller with actions, usung Entity Framework it does't show in the form for generating the API. Also if i gerate the DbContext that inheriting from DbContext it works, but after that if i chage it to ApiAuthorizationDbContex it's stops working again.

Do i have to use two DbContexts?

### Further technical details

EF Core version:  3.1.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.2
Operating system: Windows
IDE: Visual Studio 2019 16.3

**Comment by vickblack** [comment] 2020-06-19 17:54
Same problem here

**Comment by DanyGagnonPID** [comment] 2020-06-19 17:56
I'm experiencing the same thing

**Comment by GaryFurash** [comment] 2020-06-26 22:12
I have the same issue. If I use IdentityDbContext I can't scaffold a razor page. If I switch it back to DbContext I can.

**Comment by PotatoSauceVFX** [comment] 2020-06-29 03:57
Same issue here. Has this always been an issue? It seems like only recently. Scaffolding works with DbContext, but when using IdentityDbContext no options appear in the "Data context class" field. I thought it had something to do with me using MySQL, but the OP has ruled that out.

**Comment by vickblack** [comment] 2020-06-30 13:54
If you follow this link the issue is aparently fixed on the next version

https://developercommunity.visualstudio.com/content/problem/1052337/add-controller-and-add-new-scaffolded-item-dialogs.html

**Comment by PotatoSauceVFX** [comment] 2020-06-30 19:36
Just updated to 16.6.3 Community and it works now. :)

**Closed** 2020-07-01 13:15 UTC
