### ISSUE TITLE
BUG: Email Change and Confirmation Encoding mismatch

### ISSUE THREAD

**Issue by iAlexanderMoon** [dotnet/Scaffolding#1835] opened 2022-02-22 02:53 UTC
Account.ConfirmEmail.cs.cshtml expects a base64 encoded string of "code" but Account.Manage.Email.cs.cshtml is not encoding it.

src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Account.ConfirmEmail.cs.cshtml 
```C#
59:    code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
60:    var result = await _userManager.ConfirmEmailAsync(user, code);
```

src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap3/Pages/Account/Manage/Account.Manage.Email.cs.cshtml
```C#
114:   var code = await _userManager.GenerateChangeEmailTokenAsync(user, Input.NewEmail);
115:   var callbackUrl = Url.Page(

// ------------------ SHOULD BE -------------

114:   var code = await _userManager.GenerateChangeEmailTokenAsync(user, Input.NewEmail);
115:   code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
116:   var callbackUrl = Url.Page(
```

Changes in version 5.0 for Bootstrap 4 template corrected it, however, it wasn't fixed in Bootstrap 3 which is still broken on MAIN:HEAD or back ported to either Bootstrap 3 or 4 on the 3.1 branch.

* HEAD:   Bootstrap 3 [incorrect], Bootstrap 4 [correct], Bootstrap 5 [correct]
* ...
* Release 5.0:  Bootstrap 3 [incorrect], Bootstrap 4 [correct]
* Release 3.1:  Bootstrap 3 [incorrect], Bootstrap 4 [incorrect]

**Comment by vijayrkn** [comment] 2022-10-04 02:29
Since it doesn't reproduce in bootstrap 4. closing.

**Closed by vijayrkn** 2022-10-04 02:29 UTC
Labels: area-scaffolding, Not triaged, customer-reported
