### ISSUE TITLE
Swagger UI generator does not handle some C# XML documentation properly

### ISSUE THREAD

**Issue by janseris** [dotnet/Scaffolding#2137] opened 2022-12-04 16:13 UTC
There is an option for Swagger UI generator to take info from methods' common C# XML documentation tags.
In addition, Swagger UI allows us to use some Swagger-UI specific XML tags such as `<response statusCode="200">` for richer Swagger UI documentation
This allows us to add description to an API endpoint.

Some XML tags are working as intended:
- `<paramref>`

Some XML tags are not working as intended
- `<br>`
- `<inheritdoc>`
  - **this tag is especially important to be able to inherit documentation and avoid duplication and avoid desynchronization of duplicate documentation**
  - intended usage is to inherit documentation from a method in a lower layer in the system
- `<list>` with `<item` elements
  - could be mapped to `<ul>` (type bullet) or `<ol>` (type number) with `<li>` elements 

Visual Studio:
![image](https://user-images.githubusercontent.com/64279914/205501938-a3f3e49b-3a9b-4a2b-9e08-77e2bdea03b6.png)

Swagger UI:
![image](https://user-images.githubusercontent.com/64279914/205502021-21560be0-087d-4652-b578-7bc82c452bf8.png)

I am using Microsoft.VisualStudio.Web.CodeGeneration.Design 6.0.10 (newest version available for .NET 6 (LTS)).
Visual Studio Version 17.4.2 Community
ASP.NET and Web Tools   17.4.326.54890

Sample code:

https://github.com/janseris/SwaggerUIXMLDocumentationTest

If this is an issue of the package `Swashbuckle.AspNetCore`, please let me know and I will post the issue to the correct repository.

Thank you

**Comment by sharwell** [comment] 2022-12-05 12:03
Duplicate of https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1799

**Closed by sharwell** 2022-12-05 12:03 UTC
Labels: area-scaffolding, customer-reported

**Comment by janseris** [comment] 2022-12-11 22:14
@sharwell It is a duplicate but it is closed but not solved. Could you reopen the linked issue?
